kind: ConfigMap
apiVersion: v1
metadata:
  name: symlink-database
data:
  {{- if .Values.vln.database }}
  db.json: {{ .Values.vln.database | toJson }}
  {{- else if .Values.vln.database_file }}
  db.json: {{.Files.Get .Values.vln.database_file | printf "%s" | indent 4}}
  {{- else }}
  db.json: "{}"
  {{- end }}
